app/my_app/__init__.py
from flask import Flask, render_template, request

from my_app.tasks.controllers import taskRoute
from my_app.config import DevConfig


app = Flask(__name__)
app.register_blueprint(taskRoute)
app.config.from_object(DevConfig)

@app.route('/')
def hello_world() -> str:
    zone = request.args.get('zone', 'NoNe')
    return render_template('index.html',zone=zone,items=[1,2,3,4,5,6,7,8,9],task='Very important task')

app/my_app/tasks/__init__.py
from flask import Flask

app = Flask(__name__)

app/my_app/tasks/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for

taskRoute = Blueprint('tasks',__name__,url_prefix='/tasks')

tasks_list = ['task1', 'task2', 'task3', 'task4', 'task5']

@taskRoute.route('/')
def index():
    return render_template('dashboard/tasks/index.html', tasks=tasks_list)

@taskRoute.route('/<int:id>')
def show(id:int):
    return 'Show '+str(id)

@taskRoute.route('/delete/<int:id>')
def delete(id:int):
    del tasks_list[id]
    return redirect(url_for('tasks.index'))

@taskRoute.route('/create', methods=['GET', 'POST'])
def create():
    #print(request.form.get('task'))
    #print(request.args.get('task'))
    task = request.form.get('task')
   
    if task is not None :
        tasks_list.append(task)
        #return redirect('/tasks')
        return redirect(url_for('tasks.index'))
    return render_template('dashboard/tasks/create.html')

@taskRoute.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id:int):
    task = request.form.get('task')
    
    if task is not None:
        tasks_list[id] = task
        return redirect(url_for('tasks.index'))
    
    return render_template('dashboard/tasks/update.html')

app/my_app/templates/dashboard/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %} - Flask</title>
</head>
<body>
    <div>
        {% block content %}

        {% endblock %}
    </div>

    {% block footer %}
        <p>Dashboard tasks footer</p>
    {% endblock %}
    
</body>
</html>

app/my_app/templates/dashboard/tasks/create.html
{% extends "dashboard/master.html" %}

{% block title %} Create tasks {% endblock%}

{% block content %}
    <form action="" method="POST">
        <input type="text" name="task">
        <button type="submit">Send</button>
    </form>
{% endblock %}

app/my_app/templates/dashboard/tasks/index.html
{% extends "dashboard/master.html" %}

{% block title %} Index tasks {% endblock%}

{% block content %}
<a href="{{ url_for('tasks.create') }}">Create</a>
<ul>
    {% for task in tasks %}
        <li>{{ task }}</li>
        <li><a href="/tasks/update/{{ loop.index0 }}">Edit_old</a></li>
        <li><a href="{{ url_for('tasks.update', id = loop.index0) }}">Edit</a></li>
        <li><a href="{{ url_for('tasks.delete', id = loop.index0) }}">Delete</a></li>
    {% endfor %}
</ul>
{% endblock %}

app/my_app/templates/dashboard/tasks/update.html
{% extends "dashboard/master.html" %}

{% block title %} Create tasks {% endblock%}

{% block content %}
    <form action="" method="POST">
        <input type="text" name="task">
        <button type="submit">Send</button>
    </form>
{% endblock %}

app/my_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ zone }}</h1>
    <p>Testing Jinga</p>

    <h3> IF ELSEIF ENDIF</h3>
    {# Conditionals #}
    {% if zone == 'NoNe' %}
        <P> There was no zone defined </P>
    {% else %}
        <P> There was a zone defined: {{zone }} </P>
    {% endif %}

    <h3> For</h3>
    {# Statement for #}
    <ul>
    {% for item in items %}
        <li>{{ item }}-{{ loop.length }}</li>
    {% endfor %}
    </ul>

    

    <h3> Filters</h3>
    {# Filter default #}
    <p> {{ task | default('The isn`t any task defined') }} </p>

    {#
    {% if task != NULL %}
        <P> We have task! </P>
    {% endif %}
    #}


    {# Filter escape #}
    <p> {{ '<h1> Hola Munndo!</h1>' }}</p>

    {# Filter conversion #}
    <p>{{ 5.1425 | int }}</p>
    <p>{{ 5 | float }}</p>

    {# Filter max min #}
    <p>{{ [1,2,3,4,5,6] | min }}</p>
    <p>{{ [1,2,3,4,5,6] | max }}</p>

    {# Filter max min #}
    <p>{{ 5.141 | round }}</p>
    <p>{{ 5.5 | round }}</p>
    <p>{{ 6.5199 | round(2) }}</p>

    {# Filter replace #}
    <p>{{ "Hello my friend" | replace("Hello", "Hi") }}</p>

    {# Filter join #}
    <p>{{ ["Hello","my","friend"] | join("-") }}</p>

    {# Filter lower upper #}
    <p>{{ ["Hello","my","friend"] | join("-") | upper }}</p>

    {% filter lower %}
    HeLLo FLasK    
    {% endfilter %}

    {# Filter reverse #}
    <p>{{ [1,2,3,4,5,6] | reverse }}</p>
    <p>{{ "Hola my friend" | reverse }}</p>

    <ul>
    {% for x in [1,2,3,4,5,6] | reverse %}
        <li>{{ x }}</li>
    {% endfor %}
    </ul>

    {# Filter length #}
    <p>{{ [1,2,3,4,5,6] | length }}</p>
    <p>{{ "Hola my friend" | length }}</p>

    {# Filter sort #}
    <p>{{ [1.5,23,0.3,14,35,0.6] | sort }}</p>

    {# Filter slice #}
    <p>{{ [1,2,3,4,5,6] | slice(3) }}</p>

    <ul>
        {% for x in [1,2,3,4,5,6] | slice(3) %}
            <li>{{ x }}</li>
        {% endfor %}
    </ul>

    <h3> Variables</h3>

    {% set var1 = 'Flask' %}
    {% set var2 = 'Hello ' + var1 %}

    {{ var2 }}

    <h3> Bloque raw</h3>
    {% raw %}

    {% endraw %}

    <h3> Bloque macro</h3>
    {% macro suma(v1,v2) %}
    <p>{{ v1 }} + {{ v2 }} = {{ v1 + v2 }}</p>
    {% endmacro %}

    {{ suma(4, 3) }}



    





</body>
</html>